### PR TITLE
jacdac trace: add "save trace" link

### PR DESCRIPTION
**Pull request by pelikhan**
- [x] save trace anchor button in footer allows to save the jacdac trace of packets, that can be inspected and replayed in the jacdac dashboard.
- [x] build and store makecode binary as part of build
- [x] updated makecode firmware

Looks like there is no footer pointing to privacy/TOS on the page.

### CODE REVIEW

**Comment by pelikhan** [comment]
@venkateshpotluri let's try to use this to collect the jacdac trace. Additionally, if you can open the context menu in the javascript console, there is a "save as" option.

**Comment by venkateshpotluri** [comment]
@pelikhan  Thank you so much for creating this PR! I tried saving traces with both micro:bits and am still able to re-pro the issue. let's talk more when we meet. I had one question: can we make sure to display this button only when a debug boolean is set? I would like to hide this when the participant is performing the study in case they accidentally get here and mistake it as something they can use to collect data.

**Comment by pelikhan** [comment]
Now needs ?dbg=1 in the URL to be enabled.

**Comment by pelikhan** [comment]
This is ready. I will do another PR to add the start/stop the recording with the play button.

**Pull request merged**
